# Generated by Django 5.2.4 on 2025-08-31 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("thinktanks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=100)),
                ("start_url", models.URLField(max_length=500)),
                ("crawler_type", models.CharField(max_length=50)),
                (
                    "schedule_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "schedule_time",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                (
                    "last_run_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("running", "Running"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("last_run_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("crawler_config", models.TextField(blank=True, null=True)),
                (
                    "thinktank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thinktanks.thinktank",
                    ),
                ),
            ],
            options={
                "db_table": "crawl_tasks",
            },
        ),
    ]
