# Generated by Django 5.2.4 on 2025-08-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("full_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("editor", "Editor"),
                            ("admin", "Admin"),
                            ("researcher", "Researcher"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
