# Generated by Django 5.2.4 on 2025-08-31 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("thinktanks", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=255, unique=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                ("publish_date", models.DateField(blank=True, null=True)),
                ("crawl_date", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("report", "Report"),
                            ("article", "Article"),
                            ("blog", "Blog"),
                            ("press_release", "Press Release"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=255, null=True)),
                ("view_count", models.IntegerField(default=0)),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "thinktank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thinktanks.thinktank",
                    ),
                ),
            ],
            options={
                "db_table": "articles",
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("original_url", models.URLField(max_length=500)),
                ("local_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("doc", "DOC"),
                            ("ppt", "PPT"),
                            ("xlsx", "Excel"),
                            ("image", "Image"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file_size", models.IntegerField(blank=True, null=True)),
                (
                    "download_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("downloaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "db_table": "attachments",
            },
        ),
        migrations.CreateModel(
            name="Digest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digest_summary", models.TextField()),
                ("key_points", models.TextField(blank=True, null=True)),
                ("editor_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.article",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "db_table": "digests",
            },
        ),
    ]
