# Generated by Django 5.2.4 on 2025-09-22 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_digest_editor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digest",
            name="article",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="digest",
                to="articles.article",
            ),
        ),
    ]
